# Generated by Django 3.2.5 on 2021-08-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('style_image', models.TextField()),
                ('product_image', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=2)),
                ('style_products', models.TextField()),
                ('product_description', models.TextField()),
                ('product_type', models.IntegerField()),
                ('price', models.CharField(max_length=10)),
                ('usage', models.CharField(max_length=20)),
                ('product_link', models.TextField()),
                ('location', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_sale10', models.IntegerField()),
                ('month_sale10', models.IntegerField()),
                ('visit10', models.IntegerField()),
                ('week_sale20', models.IntegerField()),
                ('month_sale20', models.IntegerField()),
                ('visit20', models.IntegerField()),
                ('week_sale30', models.IntegerField()),
                ('month_sale30', models.IntegerField()),
                ('visit30', models.IntegerField()),
                ('week_sale40', models.IntegerField()),
                ('month_sale40', models.IntegerField()),
                ('visit40', models.IntegerField()),
                ('week_sale50', models.IntegerField()),
                ('month_sale50', models.IntegerField()),
                ('visit50', models.IntegerField()),
                ('week_sale60', models.IntegerField()),
                ('month_sale60', models.IntegerField()),
                ('visit60', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
