# Generated by Django 3.2 on 2021-07-29 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('style_image', models.TextField()),
                ('product_image', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=2)),
                ('style_products', models.TextField()),
                ('product_description', models.TextField()),
                ('product_type', models.IntegerField()),
                ('price', models.CharField(max_length=10)),
                ('usage', models.CharField(max_length=20)),
                ('product_link', models.TextField()),
                ('location', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
